In [2]:
import pandas as pd

In [51]:
train_df = pd.read_parquet('../data/processed/train_split_no_fss.parquet')
test_df = pd.read_parquet('../data/processed/test_split_no_fss.parquet')

In [28]:
import re

def remove_mask_tokens(text):
    return re.sub(r"\bx+\b", " ", text.lower())

X_train = train_df["Consumer complaint narrative"].apply(remove_mask_tokens)

In [29]:
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS

unique_words = set()

for text in X_train.dropna():
    words = re.findall(r"\b[a-z]+\b", text.lower())  # lowercase + remove ! and punctuation
    unique_words.update(w for w in words if w not in ENGLISH_STOP_WORDS)

unique_words

{'weeis',
 'cornon',
 'landdlord',
 'ratesthat',
 'foreclosing',
 'dothat',
 'airfares',
 'erronesoulsy',
 'limping',
 'righxxxx',
 'nucc',
 'tresses',
 'achopens',
 'pds',
 'holidaythat',
 'xxxxaws',
 'theheloc',
 'ignoredonmydisputes',
 'namesbnaselflndr',
 'helloi',
 'calumny',
 'illictly',
 'issuewith',
 'eill',
 'msot',
 'agemcy',
 'hammond',
 'officed',
 'miguel',
 'bully',
 'whit',
 'neutered',
 'communicationdemonstrating',
 'usaa',
 'dseveral',
 'mayxx',
 'learned',
 'chards',
 'readingroom',
 'umnaceptable',
 'matting',
 'tryng',
 'supposerd',
 'gfair',
 'miscategorizes',
 'agenciesincluding',
 'repitedly',
 'confirmationdemonstrating',
 'equifaax',
 'zapped',
 'fease',
 'usedthey',
 'atively',
 'faield',
 'supervisory',
 'thoughout',
 'pepeole',
 'collatio',
 'scheduledfor',
 'dintvrecieve',
 'newman',
 'slshas',
 'repsentative',
 'williston',
 'settlementwould',
 'emplore',
 'hadlivedhere',
 'ivy',
 'agencyo',
 'hemisphere',
 'libel',
 'paystubs',
 'tamping',
 'informationonly',
 'improer',
 'detoured',
 'difnt',
 'crowds',
 'presumit',
 'socspicious',
 'vivant',
 'residencyall',
 'pics',
 'everntually',
 'violationsuggests',
 'kedoning',
 'themichiganattorneygeneral',
 'weeks',
 'accccount',
 'morgen',
 'mshda',
 'tanf',
 'incidentchase',
 'paymentcredit',
 'heretowithwill',
 'differeence',
 'scoresxxxx',
 'confines',
 'idisclosure',
 'nies',
 'avoidances',
 'designators',
 'amassing',
 'gpas',
 'electronicaly',
 'livint',
 'feellike',
 'calamities',
 'tterminated',
 'bureause',
 'geiko',
 'supposedlyxxxx',
 'london',
 'alogical',
 'wavering',
 'rathered',
 'fundssubmitted',
 'firstnamelastname',
 'portection',
 'dont',
 'jonathon',
 'dothe',
 'mycredit',
 'identityproof',
 'incenuated',
 'artifacts',
 'screw',
 'mentaltitly',
 'ligit',
 'coles',
 'colleges',
 'subscrition',
 'smg',
 'selltement',
 'processign',
 'sale',
 'roofer',
 'dissgrred',
 'securemessage',
 'polyp',
 'colorectal',
 'numorious',
 'circa',
 'fraudulentinquiry',
 'callcenter',
 'setllement',
 'endowed',
 'supervisorwas',
 'debtvalidation',
 'ttansaction',
 'firstpremier',
 'seghare',
 'assumethat',
 'onlyno',
 'aftereffects',
 'xxxxvisa',
 'misrepresentationdelivered',
 'daysomeone',
 'confinement',
 'benificial',
 'infromed',
 'musi',
 'stationery',
 'bubbly',
 'xxxxts',
 'allegate',
 'predicates',
 'student',
 'departing',
 'commutated',
 'reinvestigaion',
 'erounously',
 'bmgmoneyin',
 'phytoplankton',
 'downwards',
 'mastercard',
 'island',
 'himyet',
 'bap',
 'intere',
 'bankructcy',
 'finwise',
 'accommodationsdespite',
 'ambiguously',
 'intersted',
 'soopers',
 'fhact',
 'xxxxtransunionxxxxequifaxxxxxequifaxxxxx',
 'disputesxxxxre',
 'seteris',
 'scaled',
 'aldready',
 'forbearancewhere',
 'pysically',
 'negativilty',
 'snows',
 'automactically',
 'spawned',
 'wothvny',
 'agreementsthen',
 'waiverends',
 'appology',
 'worseunauthorized',
 'overpaymentxx',
 'danage',
 'neverbsend',
 'pinked',
 'fraudrights',
 'invesitigation',
 'largents',
 'addressxxxxxxxx',
 'cycleeven',
 'cffpb',
 'pbxs',
 'artificially',
 'unseccessul',
 'procollection',
 'uping',
 'insufficiencies',
 'jasons',
 'isnpections',
 'windowxxxx',
 'fraqud',
 'limititing',
 'homeespecially',
 'personallyit',
 'oneyet',
 'nagencys',
 'deldot',
 'interferant',
 'abyssmal',
 'liebecause',
 'xxxxxxxxdated',
 'recieot',
 'understatment',
 'wyndham',
 'accuracyandintegrity',
 'recivable',
 'escelating',
 'isgoingto',
 'jermaine',
 'xxxxcitations',
 'peretti',
 'thisalsobringsintotheintegrityofethicsoftheplaintiff',
 'cerdit',
 'therer',
 'xxxxprevious',
 'compaines',
 'debated',
 'chasm',
 'microphone',
 'notificationjust',
 'paymentshave',
 'mortgageonce',
 'enrich',
 'impactful',
 'agonizingly',
 'updatedmy',
 'avide',
 'showint',
 'receiveddespite',
 'codifies',
 'pregenerated',
 'affraid',
 'inittially',
 'staircases',
 'coddle',
 'alidation',
 'mesayin',
 'vilodate',
 'diabolically',
 'review',
 'theseaccountsareresultsofidentitytheft',
 'grill',
 'somene',
 'dealierahip',
 'coinvent',
 'otter',
 'optd',
 'pounts',
 'enquirer',
 'undersigned',
 'acorridingly',
 'trebly',
 'removalspecifically',
 'ooooooooooooooooooo',
 'colfor',
 'billls',
 'placernent',
 'pamyent',
 'godhole',
 'lection',
 'importatnt',
 'advertizing',
 'pendingstatus',
 'algate',
 'failedt',
 'ofpayment',
 'padgett',
 'ik',
 'soulation',
 'stubborn',
 'camouflaged',
 'payxxxxxxxx',
 'ago',
 'screenrecord',
 'docsign',
 'clothies',
 'whod',
 'hlthfrxxxxxxxxxxx',
 'cbnc',
 'amputation',
 'durine',
 'preloadable',
 'consumerfinancexxxx',
 'telfono',
 'companubscrib',
 'activties',
 'julaug',
 'php',
 'efiled',
 'fairfor',
 'expecation',
 'fullfile',
 'portrays',
 'unknowledgeable',
 'licy',
 'fayservicing',
 'unpolitely',
 'overbuilt',
 'mishandlig',
 'winthdrawl',
 'ofreceipt',
 'itbis',
 'nwillful',
 'hindrance',
 'fran',
 'nevernave',
 'saab',
 'thatvthe',
 'ignition',
 'boutiques',
 'humidifier',
 'resovle',
 'citimobile',
 'calledme',
 'vcredit',
 'seasonally',
 'veteren',
 'tio',
 'staighten',
 'cumulus',
 'corporates',
 'episodes',
 'clanxxxx',
 'butstill',
 'cdcs',
 'boats',
 'alomst',
 'distrusting',
 'accountsshow',
 'eh',
 'exif',
 'financexxxxxxxx',
 'undersecretary',
 'etiquettes',
 'rjo',
 'presentedxxxxif',
 'crimes',
 'proceduresftc',
 'guildlines',
 'providingme',
 'acept',
 'afterto',
 'ttook',
 'fargonot',
 'dss',
 'mentionoed',
 'wagering',
 'desmond',
 'parlors',
 'neighbor',
 'thong',
 'suspiciously',
 'accountthat',
 'msrp',
 'neverminded',
 'exceptionable',
 'questionn',
 'thefraud',
 'boyfriendliving',
 'perfection',
 'rej',
 'delibritly',
 'precedingyears',
 'chargred',
 'unpeeling',
 'debti',
 'reseachincoming',
 'foreclsoure',
 'inadequates',
 'jessicas',
 'inflitration',
 'enhdanced',
 'honours',
 'mahela',
 'businesss',
 'enchaned',
 'ums',
 'suviorship',
 'unprocessed',
 'pains',
 'invesigate',
 'shedule',
 'asssoc',
 'sorrythen',
 'grown',
 'noticeafter',
 'seatled',
 'nths',
 'nreview',
 'pricless',
 'irresponsibilities',
 'unscropolous',
 'statusconfirming',
 'dentally',
 'regulative',
 'informatifrom',
 'elevaterecovery',
 'procollect',
 'idenifiers',
 'allcollections',
 'cars',
 'tormented',
 'fargona',
 'ativity',
 'accba',
 'slaten',
 'accesswhich',
 'ticketstoday',
 'reposation',
 'willingingly',
 'tape',
 'cud',
 'realsystem',
 'snuck',
 'fraudelent',
 'millestone',
 'statusdear',
 'miscellaneous',
 'underpin',
 'runaroiund',
 'scarred',
 'toldincorrectlythat',
 'californi',
 'safeguards',
 'slope',
 'greatless',
 'thelawtodoso',
 'sharpauto',
 'responseconstitutes',
 'ticked',
 'corpirate',
 'sixteen',
 'claimsmirror',
 'linchpin',
 'havebt',
 'bckgrnd',
 'accounuts',
 'sadness',
 'relics',
 'somr',
 'edrp',
 'ched',
 'custormer',
 'attorneyan',
 'aneducational',
 'mtbsignon',
 'unansweredas',
 'undetailed',
 'gly',
 'disability',
 'pmyt',
 'courteoussecond',
 'convincer',
 'temperately',
 'caslled',
 'sago',
 'bureauhas',
 'wouldlook',
 'ncspus',
 'innvois',
 'studentdatadocument',
 'kcpa',
 'xxxxma',
 'screwy',
 'alaborate',
 'farness',
 'ucted',
 'dieng',
 'altered',
 'oblations',
 'communicauon',
 'impeach',
 'warrantable',
 'coated',
 'dp',
 'thexxxxre',
 'momentforcing',
 'ort',
 'unvaccinated',
 'codate',
 'endgame',
 'factum',
 'vech',
 'maintemance',
 'opinions',
 'unfortunate',
 'notexplained',
 'explanantion',
 'furnist',
 'operandi',
 'perturbing',
 'saline',
 'tradelineincluding',
 'jinky',
 'recorede',
 'appartment',
 'unifininc',
 'disputewithin',
 'creditkarmas',
 'weird',
 'thatjust',
 'protectedright',
 'concor',
 'medies',
 'refigerator',
 'greatly',
 'worn',
 'wheras',
 'deceive',
 'ineffeciency',
 'lik',
 'inpersonam',
 'corespond',
 'soken',
 'themortgage',
 'alertly',
 'repairlikely',
 'sloping',
 'impersonations',
 'ih',
 'agoending',
 'matic',
 'nautilus',
 'exceedes',
 'disfigurement',
 'tosuggesting',
 'employer',
 'cuentas',
 'pif',
 'includeunder',
 'carvanacare',
 'pcna',
 'wonder',
 'recipientshould',
 'respentive',
 'cci',
 'conuduct',
 'loadcare',
 'esdt',
 'respone',
 'prongs',
 'legwork',
 'allxx',
 'frago',
 'beurea',
 'aegc',
 'inam',
 'hte',
 'residency',
 'disinvited',
 'avecerritos',
 'differen',
 'ennies',
 'unauthrorised',
 'believeit',
 'shittiest',
 'eneded',
 'sarly',
 'counterfiting',
 'suppurativa',
 'umpteen',
 'casw',
 'unreduced',
 'gamership',
 'hijacks',
 'tbey',
 'stimulates',
 'died',
 'arrowed',
 'furnisg',
 'instuition',
 'interactions',
 'tehnically',
 'medicorp',
 'immediatelynot',
 'annonymous',
 'pute',
 'compromised',
 'rippling',
 'ellipses',
 'commited',
 'mpla',
 'appleinsider',
 'googlewallet',
 'tyem',
 'forbearancexxxx',
 'delinquencypotentially',
 'monterey',
 'qritten',
 'irreconcilable',
 'ewuifax',
 'reportingare',
 'precisely',
 'seeen',
 'preserver',
 'polyester',
 'kepts',
 'awar',
 'xxxxtj',
 'notificationwritten',
 'coyple',
 'numerice',
 'goofy',
 'concerningaccounts',
 'opportunely',
 'yonthe',
 'discovere',
 'abstracts',
 'recibio',
 'reportmy',
 'myca',
 'alignes',
 'implied',
 'xxxxusdxxxxr',
 'assessmentnot',
 'chunk',
 'abusesxxxx',
 'smish',
 'veritied',
 'responsibilities',
 'procicute',
 'usofna',
 'theitemwaspreviouslydeletedandireceivednonoticeofre',
 'whichallegedly',
 'guardrail',
 'giant',
 'lengthy',
 'dilydallying',
 'partyand',
 'impactpurchased',
 'ncode',
 'infomaiton',
 'timley',
 'promssory',
 'petrozzini',
 'hkdxxxx',
 'documenti',
 'countines',
 'treasurt',
 'xxxxrating',
 'hallucinating',
 'progressives',
 'rmember',
 'andaybe',
 'unju',
 'works',
 'approched',
 'insulting',
 'informamon',
 'xxxxmerisave',
 'nprompt',
 'tmn',
 'decision',
 'runner',
 'crawfish',
 'btseglobal',
 'discipline',
 'theconsiderationis',
 'repeatedlty',
 'polite',
 'selfregulatory',
 'scct',
 'viloating',
 'vested',
 'forehand',
 'suitor',
 'yardsale',
 'miraculously',
 'immedly',
 'indispose',
 'wheels',
 'thaht',
 'indetified',
 'viewer',
 'coercement',
 'hfd',
 'revictimizing',
 'probelm',
 'resourses',
 'inconsitantcies',
 'nproblem',
 'bamboo',
 'allspring',
 'nearbys',
 'bonuss',
 'complaintconfirm',
 'ccrd',
 'takixxxx',
 'onlywant',
 'incompliantly',
 'xxxxwhether',
 'speacil',
 'purple',
 'telemarketers',
 'xxxxlaim',
 'txxxxn',
 'rexx',
 'thealleged',
 'obsard',
 'previoous',
 'timeallowedby',
 'dueis',
 'wand',
 'sellment',
 'expressively',
 'passkey',
 'niether',
 'oppotunity',
 'rull',
 'invistagate',
 'stringent',
 'activy',
 'thisinfo',
 'escalationnot',
 'collectible',
 'leverageable',
 'incinuation',
 'censure',
 'snapped',
 'mentions',
 'transpertaion',
 'unknoweldgeable',
 'huseman',
 'protetection',
 'homemaker',
 'topless',
 'balancecosting',
 'commissionshall',
 'payup',
 'fussed',
 'inaccu',
 'vasselee',
 'applicationon',
 'spreadsheet',
 'treble',
 'xxxxpoints',
 'purusant',
 'aspecific',
 'adandn',
 'reportsand',
 'bella',
 'personaly',
 'geor',
 'manualy',
 'permanentlyunless',
 'unintenttionally',
 'dogdy',
 'val',
 'settelment',
 'explicicty',
 'informason',
 'wile',
 'misin',
 'avarice',
 'copys',
 'accesed',
 'tribally',
 'extinction',
 'unnotified',
 'recurrent',
 'requisting',
 'leapt',
 'yourl',
 'attachin',
 'inthey',
 'responding',
 'hmds',
 'dcid',
 'xome',
 'repeatespy',
 'aftr',
 'adaptations',
 'offair',
 'satillite',
 'cowboys',
 'bucking',
 'firsst',
 'chattels',
 'retreats',
 'corperations',
 'chacked',
 'supplementation',
 'eqigax',
 'twicein',
 'borroweror',
 'perdim',
 'bellow',
 'inreached',
 'obastacle',
 'laskeside',
 'expected',
 'delthe',
 'intimacy',
 'solutiononly',
 'condolidated',
 'rediculouse',
 'sumary',
 'revecied',
 'advisordollar',
 'postbox',
 'sidebars',
 'theseunauthorized',
 'violatins',
 'sakewould',
 'violationsfailure',
 'brxxxx',
 'orgional',
 'stoleing',
 'chekrs',
 'withtitle',
 'disempowered',
 'clean',
 'reawakened',
 'xxxxefferson',
 'uniless',
 'dfdeting',
 'accussed',
 'incinerated',
 'dogethat',
 'colony',
 'slug',
 'reasoneven',
 'evoked',
 'xxxxinaccurate',
 'deville',
 'vre',
 'trustmsrks',
 'xxxxreceives',
 'causate',
 'sped',
 'allianceonce',
 'reauire',
 'loyal',
 'fulling',
 'subsquent',
 'mpowers',
 'inquiriesexcept',
 'inheriting',
 'flickered',
 'cheaters',
 'unalieable',
 'sabbotage',
 'compelted',
 'delinquencywhich',
 'oftheir',
 'equittable',
 'redirectly',
 'reportind',
 'honors',
 'reprosession',
 'beau',
 'selflead',
 'starship',
 'noticesomething',
 'unlawfulsessa',
 'maxes',
 'cps',
 'toincome',
 'columnized',
 'nmedical',
 'tlime',
 'xxxxmajr',
 'refusinf',
 'chaseor',
 'correctionits',
 'reservationincluding',
 'growcredit',
 'errorounlsy',
 'trucking',
 'anterior',
 'illustration',
 'preplanned',
 'disquiet',
 'sorrywe',
 'unfeasiblethe',
 'end',
 'licensefromthatplace',
 'rightsnone',
 'control',
 'cashing',
 'becasuse',
 'failedeither',
 'triu',
 'copywriter',
 'extimate',
 'flexpay',
 'secondlate',
 'regularize',
 'itsmy',
 'simu',
 'xxxxsilly',
 'todaysomething',
 'texa',
 'parisian',
 'theheirs',
 'cancun',
 'panicking',
 'forgedit',
 'tossing',
 'schedualed',
 'exported',
 'varifying',
 'irreversable',
 'allocate',
 'directlyon',
 'afncorp',
 'toronto',
 'freshly',
 'logbooks',
 'debtied',
 'info',
 'mary',
 'lamentably',
 'cbras',
 'inverse',
 'xxxxxxxxare',
 'fountain',
 'systemupon',
 'supeonable',
 'fayservicings',
 'dealersshio',
 'wwinbfotvthem',
 'xxxxsince',
 'unincorporated',
 'cellspot',
 'filesthey',
 'unbiassed',
 'reclaimed',
 'forgetting',
 'favov',
 'apoplexy',
 'mortgageisnot',
 'possibl',
 'gress',
 'dueat',
 'ndisregarded',
 'uesting',
 'combined',
 'gien',
 'presitents',
 'infructuous',
 'suborned',
 'coninsendially',
 'copacetic',
 'decimated',
 'statementsxxxx',
 'myportal',
 'paymentdated',
 'fraudulnet',
 'emsquickenxxxx',
 'datre',
 'reproing',
 'guysaid',
 'imeditaly',
 'pled',
 'restraunt',
 'reinstitute',
 'bankagreed',
 'helen',
 'jeeep',
 'holmberg',
 'devos',
 'finiancial',
 'soory',
 'flutter',
 'scary',
 'fraudlentuly',
 'disclosedmaking',
 ...}

In [30]:
from collections import Counter

bigram_counter = Counter()

for text in X_train.dropna():
    words = [w for w in re.findall(r"\b[a-z]+\b", text.lower()) if w not in ENGLISH_STOP_WORDS]
    bigrams = zip(words, words[1:])
    bigram_counter.update(bigrams)

bigram_counter.most_common(50)

[(('credit', 'report'), 755842),
 (('u', 's'), 537396),
 (('credit', 'reporting'), 402860),
 (('s', 'c'), 369434),
 (('identity', 'theft'), 271345),
 (('fair', 'credit'), 264267),
 (('consumer', 'reporting'), 250277),
 (('reporting', 'act'), 248456),
 (('reporting', 'agency'), 243967),
 (('account', 'number'), 173278),
 (('section', 'states'), 156455),
 (('s', 'code'), 155243),
 (('credit', 'bureaus'), 150049),
 (('c', 'section'), 145712),
 (('consumer', 'report'), 145371),
 (('credit', 'card'), 125559),
 (('information', 'credit'), 113235),
 (('account', 'account'), 103935),
 (('late', 'payment'), 103482),
 (('personal', 'information'), 99412),
 (('states', 'consumer'), 99370),
 (('reporting', 'agencies'), 97976),
 (('credit', 'reports'), 89591),
 (('inaccurate', 'information'), 89370),
 (('act', 'fcra'), 89038),
 (('credit', 'file'), 87464),
 (('late', 'payments'), 85158),
 (('right', 'privacy'), 76852),
 (('agency', 'furnish'), 72939),
 (('consumer', 'credit'), 72535),
 (('date', 'opened'), 71092),
 (('written', 'instructions'), 69645),
 (('section', 'section'), 67643),
 (('accordance', 'fair'), 66319),
 (('furnish', 'account'), 63464),
 (('business', 'days'), 62967),
 (('account', 'written'), 62837),
 (('credit', 'score'), 62122),
 (('original', 'creditor'), 61997),
 (('states', 'right'), 60177),
 (('hard', 'inquiries'), 59596),
 (('information', 'inaccurate'), 59525),
 (('victim', 'identity'), 58790),
 (('consumer', 'rights'), 58217),
 (('consumer', 'consumer'), 57919),
 (('privacy', 'u'), 54961),
 (('customer', 'service'), 54670),
 (('consumer', 'financial'), 53181),
 (('item', 'information'), 52931),
 (('removed', 'credit'), 52510)]

In [14]:
bigram_counter.most_common(100)[50:100]

[(('debt', 'collection'), 52255),
 (('financial', 'protection'), 51992),
 (('payment', 'history'), 51946),
 (('violated', 'rights'), 51733),
 (('consumer', 'reports'), 51694),
 (('fraudulent', 'accounts'), 51069),
 (('wells', 'fargo'), 51066),
 (('fcra', 'u'), 50825),
 (('federal', 'law'), 50722),
 (('result', 'identity'), 50100),
 (('legal', 'action'), 49452),
 (('accounts', 'credit'), 49181),
 (('don', 't'), 48967),
 (('furnish', 'information'), 48107),
 (('following', 'items'), 47394),
 (('opened', 'balance'), 47251),
 (('information', 'relating'), 47054),
 (('federal', 'trade'), 46820),
 (('filing', 'complaint'), 46168),
 (('social', 'security'), 45954),
 (('alleged', 'debt'), 45469),
 (('trade', 'commission'), 43271),
 (('relating', 'consumer'), 43138),
 (('written', 'consent'), 42505),
 (('agency', 'person'), 42366),
 (('believe', 'information'), 42195),
 (('credit', 'bureau'), 42008),
 (('reasonable', 'cause'), 41988),
 (('protected', 'consumer'), 41961),
 (('cause', 'believe'), 41900),
 (('number', 'account'), 41207),
 (('federally', 'protected'), 41081),
 (('shall', 'furnish'), 40630),
 (('rights', 'privacy'), 40614),
 (('person', 'shall'), 40578),
 (('balance', 'balance'), 40500),
 (('person', 'knows'), 40461),
 (('knows', 'reasonable'), 40458),
 (('protection', 'bureau'), 38900),
 (('date', 'inquiry'), 38755),
 (('n', 't'), 37802),
 (('account', 'credit'), 37748),
 (('theft', 'report'), 37444),
 (('reporting', 'credit'), 37120),
 (('collection', 'practices'), 36929),
 (('violation', 'fcra'), 36894),
 (('privacy', 'confidentiality'), 36778),
 (('items', 'information'), 36635),
 (('information', 'records'), 36297),
 (('reporting', 'inaccurate'), 36233)]

In [15]:
target_bigrams = [
    ("identity", "theft"),
    ("fraudulent", "accounts"),
    ("unauthorized", "charges"),
    ("account", "locked"),
    ("cannot", "access")
]

for bg in target_bigrams:
    if bg in bigram_counter:
        print(bg, bigram_counter[bg])

('identity', 'theft') 271345
('fraudulent', 'accounts') 51069
('unauthorized', 'charges') 3188
('account', 'locked') 1917

In [16]:
keywords = {"fraud", "fraudulent", "identity", "unauthorized", "stolen", "hacked", "scam"}

candidates = [
    (bg, count)
    for bg, count in bigram_counter.items()
    if bg[0] in keywords or bg[1] in keywords
]

sorted(candidates, key=lambda x: x[1], reverse=True)[:50]

[(('identity', 'theft'), 271345),
 (('victim', 'identity'), 58790),
 (('fraudulent', 'accounts'), 51069),
 (('result', 'identity'), 50100),
 (('theft', 'fraud'), 35815),
 (('unauthorized', 'inquiries'), 24231),
 (('unauthorized', 'accounts'), 22124),
 (('ftc', 'identity'), 21199),
 (('fraudulent', 'items'), 21148),
 (('fraudulent', 'information'), 20896),
 (('fraudulent', 'account'), 19821),
 (('remove', 'fraudulent'), 14693),
 (('fraud', 'business'), 14110),
 (('fraud', 'department'), 11476),
 (('fraudulent', 'inaccurate'), 11449),
 (('resulting', 'identity'), 11311),
 (('fraudulent', 'activity'), 10939),
 (('alleged', 'identity'), 10369),
 (('fraudulent', 'inquiries'), 9706),
 (('proof', 'identity'), 9534),
 (('fraudulent', 'hard'), 9361),
 (('theft', 'identity'), 9309),
 (('fraud', 'attached'), 9169),
 (('inquiries', 'fraudulent'), 8641),
 (('inaccurate', 'unauthorized'), 8641),
 (('address', 'fraud'), 8504),
 (('considered', 'identity'), 8440),
 (('complaint', 'fraudulent'), 8430),
 (('fraud', 'platform'), 8337),
 (('resulted', 'fraudulent'), 7964),
 (('fraud', 'alert'), 7894),
 (('consent', 'fraud'), 7712),
 (('identity', 'stolen'), 7704),
 (('fraudulent', 'collections'), 7690),
 (('unauthorized', 'inquiry'), 7469),
 (('unauthorized', 'hard'), 7099),
 (('removal', 'fraudulent'), 6903),
 (('unauthorized', 'use'), 6840),
 (('block', 'fraudulent'), 6759),
 (('verify', 'identity'), 6686),
 (('identity', 'federal'), 6617),
 (('fraudulent', 'charges'), 6453),
 (('illegal', 'fraudulent'), 6240),
 (('report', 'fraudulent'), 6143),
 (('fraudulent', 'equitable'), 5938),
 (('copy', 'identity'), 5863),
 (('reporting', 'fraudulent'), 5717),
 (('report', 'identity'), 5322),
 (('dispute', 'fraudulent'), 5182),
 (('unauthorized', 'credit'), 5009)]

Priority Feature Engineering

In [41]:
# -------- IMMEDIATE --------
immediate_core = [
    "identity",
    "fraud",
    "fraudulent",
    "theft",
    "scam",
    "breach",
    "phishing",
    "impersonation",
    "hacking",
    "compromise",
    "unauthorized"
]

immediate_follow = [
    "steal","stole","stolen","stealing",
    "hack","hacked","hacking",
    "use","used","using",
    "open","opened","opening",
    "create","created","creating",
    "access","accessed","accessing",
    "charge","charged","charging",
    "withdraw","withdrew","withdrawn",
    "transfer","transferred"
]


# -------- SAME DAY --------
same_day_core = [
    "access",
    "login",
    "log in",
    "account",
    "payment",
    "transaction"
]

same_day_follow = [
    "cannot","can not","can't",
    "unable",
    "locked",
    "blocked",
    "failed",
    "declined",
    "pending",
    "stuck"
]


# -------- PRIORITY FUNCTION --------
def assign_priority(text):
    text = text.lower()

    if any(c in text for c in immediate_core) and any(v in text for v in immediate_follow):
        return "immediate"

    if any(c in text for c in same_day_core) and any(v in text for v in same_day_follow):
        return "same_day"

    return "regular"

In [33]:
X_train = X_train.to_frame()

In [42]:
X_train["priority"] = X_train['Consumer complaint narrative'].apply(assign_priority)

In [43]:
X_train.head()

,Consumer complaint narrative,priority
0,"i am aware that you have been responding to many of the disputes, complaints, and challenges with pre-written standard form letters, despite the precise information consumers have provided. i am well aware that this is illegal ; as each consumer dispute must be addressed individually and dealt with in accordance with its particular merits. my letters have been written and generated using accessible software that is available to everyone. if you choose not to process or address my letters, you are violating 15 u.s. code 5 1681i. it is against the law to delay the processing of letters from consumers based on the assumption that assistance from a third party may be available. this does not qualify as a legal exception. i am the sole author of any letters bearing my name, or they have been written by my advisors with my complete knowledge and consent. i understand that there is no requirement for you to request a power of attorney to delay processing consumer letters. if you fail to process my letters promptly, i will consider it as a deliberate disregard for my consumer rights. in such a case, i must contact my attorney and pursue legal action. \n\nheres the list of the questionable items : - account numberxxxx i don't recall having late payments on this account - account please verify and validate all data for this unproven claim including the requisite certifiable compliant reporting format standard ( s ) and processes related. please remove or prove! even document all dates and balances, personal identifiers, the 426 characters of the p6 statement, and all of its trailing fragments, and any other necessary aspect of factual reporting - account numberxxxx please remove it from my public record - account number: please supply information on how you have verified this item. \n - account numberxxxx this is not mine.",regular
1,"i am submitting this complaint myself and there is no third party involved. i attached letters to let you know more in detail about what they are reporting in my credit report. they reported inaccurate information in my credit report with inconsistent and untimely dates reported across the three bureaus, transunion, , and .",regular
2,"opened . , {$12000.00} i called this company left a message for someone to call me back they never called and still reporting. \n opened , {$160.00} i spoke with an representative and told them i dont recalled doing business with them send me a signed signature of the application they never send it. \nmedical data systems opened , {$2200.00} i spoke with an representative and told them i dont recalled doing business with them send me a signed signature of the application they never send it.",regular
3,"when this account was opened, i was a minor child at the age of . the accounts listed does not belong to me and are a result of identity theft. i have shown proof of my identity and that i was a minor child at the time the accounts were opened and the companies failed to investigate and see that i was a minor and could not have opened these accounts. they are refusing to remove collection accounts that do not belong to me. i have no knowledge of this account.",immediate
4,"i contacted each company regarding illegally pulled hard inquiry. each confirmed sent them my information and no inquiry shouldve been pulled. all inquires still remains, several are doubled on my report.",regular

In [36]:
pd.set_option("display.max_colwidth", None)

X_train[["Consumer complaint narrative", "priority"]].head(15)

,Consumer complaint narrative,priority
0,"i am aware that you have been responding to many of the disputes, complaints, and challenges with pre-written standard form letters, despite the precise information consumers have provided. i am well aware that this is illegal ; as each consumer dispute must be addressed individually and dealt with in accordance with its particular merits. my letters have been written and generated using accessible software that is available to everyone. if you choose not to process or address my letters, you are violating 15 u.s. code 5 1681i. it is against the law to delay the processing of letters from consumers based on the assumption that assistance from a third party may be available. this does not qualify as a legal exception. i am the sole author of any letters bearing my name, or they have been written by my advisors with my complete knowledge and consent. i understand that there is no requirement for you to request a power of attorney to delay processing consumer letters. if you fail to process my letters promptly, i will consider it as a deliberate disregard for my consumer rights. in such a case, i must contact my attorney and pursue legal action. \n\nheres the list of the questionable items : - account numberxxxx i don't recall having late payments on this account - account please verify and validate all data for this unproven claim including the requisite certifiable compliant reporting format standard ( s ) and processes related. please remove or prove! even document all dates and balances, personal identifiers, the 426 characters of the p6 statement, and all of its trailing fragments, and any other necessary aspect of factual reporting - account numberxxxx please remove it from my public record - account number: please supply information on how you have verified this item. \n - account numberxxxx this is not mine.",regular
1,"i am submitting this complaint myself and there is no third party involved. i attached letters to let you know more in detail about what they are reporting in my credit report. they reported inaccurate information in my credit report with inconsistent and untimely dates reported across the three bureaus, transunion, , and .",regular
2,"opened . , {$12000.00} i called this company left a message for someone to call me back they never called and still reporting. \n opened , {$160.00} i spoke with an representative and told them i dont recalled doing business with them send me a signed signature of the application they never send it. \nmedical data systems opened , {$2200.00} i spoke with an representative and told them i dont recalled doing business with them send me a signed signature of the application they never send it.",regular
3,"when this account was opened, i was a minor child at the age of . the accounts listed does not belong to me and are a result of identity theft. i have shown proof of my identity and that i was a minor child at the time the accounts were opened and the companies failed to investigate and see that i was a minor and could not have opened these accounts. they are refusing to remove collection accounts that do not belong to me. i have no knowledge of this account.",immediate
4,"i contacted each company regarding illegally pulled hard inquiry. each confirmed sent them my information and no inquiry shouldve been pulled. all inquires still remains, several are doubled on my report.",regular
5,"im asking for your assistance to investigate accounts from these companies that inaccurately report late payments. ive reviewed my credit report and found entries showing late payments where there shouldnt be anythese should not appear. please remove those remarks and correct the accounts to reflect a positive status, as previously agreed.",regular
6,"in accordance with the fair credit reporting act. the list of accounts below has violated my federally protected consumer rights to privacy and confidentiality under usc . \n\n u.s. section a. states i have the right to privacy. \n\n u.s.c section a section : it also states a consumer reporting agency can not furnish a account without my written instructions u.s.c . ( a ) ( ) states : no consumer reporting agency may make any consumer report containing any of the following items of information any other adverse item of information, other than records of convictions of crimes which antedates the report by more than years. \n\n u.s.c. ( a ) ( ) a person shall not furnish any information relating to a consumer to any consumer reporting agency if the person knows or has reasonable cause to believe that the information is inaccurate.",regular
7,"i am distressed that you have included the below information in my credit profile and have failed to maintain reasonable procedures in your operations to ensure the maximum possible accuracy in the credit reports you publish. credit reporting laws ensure that bureaus report only 100 % accurate credit information. every step must be taken to assure the information reported is completely accurate and correct. therefore the following information needs to be investigated. i respectfully request to be provided proof of this alleged item, specifically the contract, note or other instrument bearing my signature. failing that, the item must be deleted from the report as soon as possible : balanced {$12000.00} balanced {$8200.00} balanced {$0.00}",regular
8,"santander bank, my mortgage company, has failed to apply a check for my mortgage. i have provided a copy of the cancelled check showing that they cashed it on with my mortgage number typed on it by them. i contacted them on / / when i was informed in the mail about the missed payment. i was told to email a copy of the cancelled check to a customer service email. they assured me they'd expedited it as their normal business practice is to take 5-7 days to research these issues. i emailed the cancelled check. i called back on / / because i received a new notice in the mail. i was told this was the first they had heard of it and was provided with a different customer service email address to send my cancelled check as proof that payment had been sent. both times the customer service agents stated they would contact me to follow up. i did receive an auto-response from the customer service email letting me know they'd received my message so i know they have the copy of the check they cashed on . i called today / / and was told they had until / / to inform me about their resolution. during all of this, to add to the frustration, their customer service agents have left me on hold for more than 10 minutes and one even hung up on me after having me hold for that long and every time i call i have to go through the entire issue as if they have no record of it. i just spoke with a supervisor and once again was assured i will hear back from her. there has been no return call as of yet.",regular
9,"good afternoon, so i applied for and got denied. the reason was chexsystems reporting that my account is unpaid and accurate from . i sent chexsystems a proof of me making payment to and account is paid and full. i cant open a bank account because this information is not deleted off chexsystems.",regular
10,someone is stealing my identity,regular
11,"credit inquiries are the most common ways a bad actor, hacker, impersonator, or other entity uses to gain inappropriate, illegal, unlawful, unauthorized, and credit without resent. there has been a warning on my report to not approve such things. my credit report with equifax is a complete mess, full of inaccuracies, and they have chosen not to deal with it. this is unacceptable. any fraudulent, illegal, illicit, unlawful, inappropriate, unauthorized, no consent, no permission from myself, is not considered a valid reason to grant credit, credit access, credit inquiries, and other things. these entries should and shall be removed. \n\ni have been locked out and i am unable to have my account restored, even though i am paying a monthly subscription fee to equifax. i can not get access. my score reports back as ""? '' and everything is hidden, unavailable, or technical errors pop up. i have talked with equifax many times, i have verified myself over the phone, they have acknowledge they are in receipt of my unlock requests, yet, i still can not gain access to my account, credit report, score, or any other credit related information. i am 100 % locked out and i can not do anything about it and equifax refuses to resolve the issue,",regular
12,"i write regarding recent reports that department of government efficiency ( doge ) has infiltrated the department of education ( ed or the department ) and that doge '' staffers have gained access to federal student loan data, which includes personal information for millions of borrowers. \nthe federal governments student loan database contains highly sensitive information for millions of borrowers, including social security numbers, marital status, and income information. as a federal loan borrower myself, this violates the contracts that were signed, and i believe them to be void now.\n\nthe access provided to doge-affiliated staff by the department may also violate the privacy act, 5 u.s.c. 552a, which, absent permission from the affected individuals, generally prohibits the disclosure of such information and requires agencies to follow rules of conduct and maintain systems with appropriate administrative, technical, and physical safeguards. \n\ni did not give doge or any of its affiliates permission to access this private data and therefore request that the null and void contracts with the department of education be removed from my accounts. please let me know if you need any information from me to validate these claims.",regular
13,"on monday i tried to withdraw {$1000.00} dollars off of my bank of america prepaid card inside in bank of america via a teller and the card was declined stating "" insufficient funds '' which false due to the fact that i did indeed have the {$1000.00} on my bank of american prepaid card. i called and spoke to a bank of america representative through the customer service line and she checked and saw there was a block on my card and she unblocked the card so i could use my funds. on tuesday / / of 2021 i went to a gas station inside with the clerk and i asked for {$7.00} on the pump for gas and my card was declined again i called bank of america customer service and the representative stated their was a glitch in the system which was causing the card to be blocked and then they unblocked the card the representative stated that someone requested that i was sent out a new card which i have never requested! and i still wasn't able to use funds. on thursday i went to another bank america location to withdraw {$13.00} which was declined. i called bank of america customer service the representative stated they had unblocked my card again and couldn't understand why the card was blocked. today saturday my card is still blocked and i'm still unable to withdraw and/or use my funds i have been speaking to bank if america representatives all day the representative stated error code pops up while trying to unblock my code and they can see that it's blocked but it has no reason why. and no one can explain why the card keeps going on block.",regular
14,"account . i have not supplied proof under the doctrine of estoppels by silence, ( mo ) , , i may presume that no proof of the alleged debt, nor therefore any such debt, in fact exists. have already deleted the fraudulent account! all requirements id with the report. you are required by law to remove this account no later than four days. this account is involved in litigation.",immediate

In [44]:
X_train['priority'].value_counts()

priority
regular      672001
immediate    262644
same_day     187809
Name: count, dtype: int64

In [52]:
X_test = test_df["Consumer complaint narrative"].apply(remove_mask_tokens)

In [53]:
X_test = X_test.to_frame()

In [54]:
X_test["priority"] = X_test['Consumer complaint narrative'].apply(assign_priority)

In [57]:
X_test.describe()

,Consumer complaint narrative,priority
count,280613,280613
unique,218652,3
top,"in accordance with the fair credit reporting act. the list of accounts below has violated my federally protected consumer rights to privacy and confidentiality under 15 usc 1681.\n\n15 u.s.c 1681 section 602 a. states i have the right to privacy.\n\n15 u.s.c 1681 section 604 a section 2 : it also states a consumer reporting agency can not furnish a account without my written instructions 15 u.s.c 1681c. ( a ) ( 5 ) section states : no consumer reporting agency may make any consumer report containing any of the following items of information any other adverse item of information, other than records of convictions of crimes which antedates the report by more than seven years.\n\n15 u.s.c. 1681s-2 ( a ) ( 1 ) a person shall not furnish any information relating to a consumer to any consumer reporting agency if the person knows or has reasonable cause to believe that the information is inaccurate.",regular
freq,2016,168223

In [62]:
train_df = train_df.drop(columns=["Product"])
train_df["priority"] = X_train["priority"]

In [63]:
train_df.head()

,complaint_id,Consumer complaint narrative,priority
0,1038908,"I am aware that you have been responding to many of the disputes, complaints, and challenges with pre-written standard form letters, despite the precise information consumers have provided. I am well aware that this is ILLEGAL ; as each consumer dispute must be addressed individually and dealt with in accordance with its particular merits. My letters have been written and generated using accessible software that is available to everyone. If you choose not to process or address my letters, you are violating 15 U.S. Code 5 1681i. It is against the law to delay the processing of letters from consumers based on the assumption that assistance from a third party may be available. This does not qualify as a legal exception. I am the sole author of any letters bearing my name, or they have been written by my advisors with my complete knowledge and consent. I understand that there is no requirement for you to request a Power of Attorney to delay processing consumer letters. If you fail to process my letters promptly, I will consider it as a deliberate disregard for my consumer rights. In such a case, I must contact my attorney and pursue legal action. \n\nHeres the list of the questionable items : XXXX XXXX XXXX - Account NumberXXXX I don't recall having late payments on this account XXXX XXXX XXXX - Account XXXX Please verify and validate all data for this unproven claim including the requisite certifiable XXXX XXXX Compliant Reporting Format Standard ( s ) and processes related. Please REMOVE or PROVE! Even document all dates and balances, personal identifiers, the 426 characters of the P6 statement, and all of its trailing fragments, and any other necessary aspect of factual reporting XXXX - Account NumberXXXX Please remove it from my public record XXXX - Account Number:XXXX Please supply information on how you have verified this item. \nXXXX XXXX XXXX - Account NumberXXXX This is not mine.",regular
1,341296,"I am submitting this complaint myself and there is no third party involved. I attached letters to let you know more in detail about what they are reporting in my credit report. They reported inaccurate information in my credit report with inconsistent and untimely dates reported across the three Bureaus, Transunion, XXXX, and XXXX.",regular
2,52674,"XXXX XXXX XXXX opened XXXX. XXXX, XXXX {$12000.00} I called this company left a message for someone to call me back they never called and still reporting. \nXXXX XXXX opened XXXX XXXX, XXXX {$160.00} I spoke with an representative and told them I dont recalled doing business with them send me a signed signature of the application they never send it. \nMEDICAL DATA SYSTEMS opened XXXX XXXX, XXXX {$2200.00} I spoke with an representative and told them I dont recalled doing business with them send me a signed signature of the application they never send it.",regular
3,1244099,"When this account was opened, I was a minor child at the age of XXXX XXXX XXXX. The accounts listed does not belong to me and are a result of identity theft. I have shown proof of my identity and that I was a minor child at the time the accounts were opened and the companies failed to investigate and see that I was a minor and could not have opened these accounts. They are refusing to remove collection accounts that do not belong to me. I have no knowledge of this account.",immediate
4,281,"I contacted each company regarding illegally pulled hard inquiry. Each confirmed XXXX sent them my information and no inquiry shouldve been pulled. All inquires still remains, several are doubled on my report.",regular

In [59]:
test_df = test_df.drop(columns=["Product"])
test_df["priority"] = X_test["priority"]

In [61]:
test_df.head()

,complaint_id,Consumer complaint narrative,priority
0,452450,See list of enquiries on my credit that I did not authorize and I know nothing about. \n\nXXXX XXXX XXXX XXXX XX/XX/XXXX & XX/XX/XXXX XXXX XXXX ( all banks ) XX/XX/XXXX XXXX XXXX XXXX XXXX XX/XX/XXXX,regular
1,862183,"I am unable to add my income information to my Experian Credit profile for over 90 days. I have brought this to Experian 's attention and it was assigned to Experian 's engineers and product team, according to Experian. They have no timeline of when this will be resolved nor an explanation of why it is occurring. In my opinion there is a promotional block on my credit profile internally, that they do not know how to remove.\n\nWithout being able to add my income information, it prevents me from being able to access and interpret all of the features of my credit file that resides with Experian. It also is blocking other companies from being able to view my credit file and determine eligibility for credit products. This is discrimination. XXXX other members of my very own household have absolutely XXXX problem adding their income information to their credit profiles and as a result, they are not blocked from potential creditors checking their reports for eligibility of certain credit products. \n\nI have inquired repeatedly for several months about the resolution of this and they continue to acknowledge it exists but will not resolve it or provide a timeline of when it will be resolved. Additionally I received a postcard from Experian on XX/XX/2024 telling me that Experian has removed my name from the preapproved credit offer mailing list for 5 years. I never requested this. I also am including a front and back copy of the postcard received.",same_day
2,331787,"The dispute for the account with XXXX XXXX XXXX that starts with XXXX has been received and should be completed by XXXX. \n\nSource : Experian Date Submitted : XX/XX/year> Estimated Resolution Date : XX/XX/year> Report Number : XXXX Account Number : XXXX XXXX : XXXX XXXX XXXX Address : XXXX XXXX XXXX XXXX XXXX, XXXX XXXX NV XXXX None : XXXX What now? \n\nWe'll process the disputed items with the data furnisher or vendor that collected the information from a public record. You'll receive alerts when updates are available and when your full results are ready to view. \n\nVisit dispute center",regular
3,1197086,ATM card stolen. Bank not honoring law regarding burden of proof and reporting requirements. Action will also be filed with the Office of the Comptroller of the Currency.,regular
4,1067230,"In accordance with the Fair Credit Reporting act. The List of accounts below has violated my federally protected consumer rights to privacy and confidentiality under 15 USC 1681.\n\n15 U.S.C 1681 section 602 A. States I have the right to privacy.\n\n15 U.S.C 1681 Section 604 A Section 2 : It also states a consumer reporting agency can not furnish a account without my written instructions 15 U.S.C 1681c. ( a ) ( 5 ) Section States : no consumer reporting agency may make any consumer report containing any of the following items of information Any other adverse item of information, other than records of convictions of crimes which antedates the report by more than seven years.\n\n15 U.S.C. 1681s-2 ( A ) ( 1 ) A person shall not furnish any information relating to a consumer to any consumer reporting agency if the person knows or has reasonable cause to believe that the information is inaccurate.",same_day

Save Data With Priority Column Added

In [65]:
train_df.to_parquet("../data/processed/priority_train.parquet", index=False)
test_df.to_parquet("../data/processed/priority_test.parquet", index=False)